// <auto-generated />
using ContactFinder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactFinder.Migrations
{
    [DbContext(typeof(ContactFinderContext))]
    [Migration("20211205181605_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ContactFinder.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Department")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CompanyName = "Intel.com",
                            Department = "HR",
                            Email = "leena.mammoth@gmail.com",
                            FirstName = "Leena",
                            LastName = "Mammoth",
                            Location = "US"
                        },
                        new
                        {
                            ContactId = 2,
                            CompanyName = "Infosys.com",
                            Department = "HR",
                            Email = "jerry.kej@gmail.com",
                            FirstName = "Jerry",
                            LastName = "Kej",
                            Location = "IND"
                        },
                        new
                        {
                            ContactId = 3,
                            CompanyName = "Nike.com",
                            Department = "HR",
                            Email = "erik.debil@gmail.com",
                            FirstName = "Erik",
                            LastName = "Debil",
                            Location = "US"
                        },
                        new
                        {
                            ContactId = 4,
                            CompanyName = "Synopys.com",
                            Department = "HR",
                            Email = "shiny.lee@gmail.com",
                            FirstName = "Shiny",
                            LastName = "Lee",
                            Location = "UK"
                        },
                        new
                        {
                            ContactId = 5,
                            CompanyName = "Intel.com",
                            Department = "HR",
                            Email = "dev.addi@gmail.com",
                            FirstName = "Dev",
                            LastName = "Addi",
                            Location = "Uk"
                        },
                        new
                        {
                            ContactId = 7,
                            CompanyName = "Jamasoftware.com",
                            Department = "HR",
                            Email = "mwigen@jamasoftware.com",
                            FirstName = "Madeline",
                            LastName = "Wigen",
                            Location = "US"
                        },
                        new
                        {
                            ContactId = 8,
                            CompanyName = "Puppet.com",
                            Department = "HR",
                            Email = "claire.hernandez@puppet.com",
                            FirstName = "Claire",
                            LastName = "Hernandez",
                            Location = "US"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
